### ISSUE TITLE
Is this project deprecated? Please add a notice

### ISSUE THREAD

**Issue by dmaciel** [projectatomic/containerd#13]
Hi

I stumbled in this project looking for a container-d cli tool, since the last activity is from 4 years ago I will assume the project is dead. The link to the "Releases" (pointing to the docker container-d repo) and the project web page are giving 404

It will be possible to add a deprecation notice and point user to the right place?, or archive the repo so it can be easily notice this is not the right project?

**Comment by RichardoC** [comment]
@crosbymichael is this something you could do?

**Comment by rhatdan** [comment]
Yes.  You should go to the main containerd repo.
